name: sendbird_sdk
description: The Flutter SDK for Sendbird Chat brings modern messenger chat
  features to your iOS and Android deployments
version: 3.1.12
homepage: https://www.sendbird.com
repository: https://www.github.com/sendbird/sendbird-sdk-flutter
documentation: https://sendbird.com/docs/chat/v3/flutter/quickstart/send-first-message

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"

platforms:
  android:
  ios:
  web:

dependencies:
  collection: ^1.15.0
  connectivity_plus: ^2.2.0
  encrypt: ^5.0.0
  flutter:
    sdk: flutter
  http: ^0.13.4
  http_parser: ^4.0.0
  json_annotation: ^4.0.0
  logger: ^1.0.0
  meta: ^1.3.0
  mime: ^1.0.0
  shared_preferences: ^2.0.0
  universal_io: ^2.0.4
  uuid: ^3.0.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  intl: null
  json_serializable: ^6.1.4
  lints: ^1.0.1
  stack_trace: ^1.9.6
  test: ^1.16.0
